# Site settings
title: test title
email: kimkaralekas@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://localhost:8080"
github_username:  kimkaralekas

# Nav settings
navigation: 
- title: Home
url: /index.html
- title: Shop
url: /shop.html
- title: About
url: /about.html
- title: Contact
url: /contact.html
- title: FAQ
url: /faq.html


# Build settings
markdown: kramdown
permalink: pretty

port: 8080
